### ISSUE TITLE
Commit Triggers: First observation or deferred by 1

### ISSUE THREAD

**Issue by seglo** [akka/alpakka-kafka#1091] opened 2020-04-02 21:00 UTC
### Short description

Add a new `CommitterSetting` that allows the user to choose whether to eagerly commit `Committables` as soon as they're observed, or once a new commit is observed.

### Details

A simple way to ensure that all transformed elements are processed when a source offset is transformed into many elements is to wait to commit an offset until the next `Committable` is observed.  This ensures at-least-once guarantees when input elements are 1:M with output elements. The consequence is that committing will always be behind-by-1 and more records may need to be reprocessed after a failure/shutdown.

**Comment by ennru** [comment] 2020-04-24 07:04
Duplicate of #1091 and #1060, implemented in #1093.

**Closed by ennru** 2020-04-24 07:04 UTC
