### ISSUE TITLE
Consumer.plainSource takes 30s to shut down

### ISSUE THREAD

**Issue by francisdb** [akka/alpakka-kafka#833] opened 2019-06-20 12:30 UTC
### Versions used 

Alpakka kafka 1.0.4
Akka 2.5.23

### Expected Behavior

consumer source shutdown future completes directly after the source itself completes

### Actual Behavior

It takes exactly 30s between the stream complete and the shutdown request complete and a dead letter is observed (see logs)

### Relevant logs

```
[info] 14:18:28.008 INFO  - o.a.kafka.common.utils.AppInfoParser - Kafka version : 2.1.1
[info] 14:18:28.008 INFO  - o.a.kafka.common.utils.AppInfoParser - Kafka commitId : 21234bee31165527
[info] 14:18:28.129 INFO  - org.apache.kafka.clients.Metadata    - Cluster ID: Rh010jjUQE2Kswmavm8Umw
[info] 14:18:28.129 INFO  - org.apache.kafka.clients.Metadata    - Cluster ID: Rh010jjUQE2Kswmavm8Umw
[info] 14:18:28.190 INFO  - o.a.k.clients.producer.KafkaProducer - [Producer clientId=producer-1] Closing the Kafka producer with timeoutMillis = 60000 ms.
[info] 14:18:28.198 INFO  - i.w.e.runtime.kafka.KafkaRuntime$    - Producer done: Success(Done)
[info] 14:18:28.262 INFO  - i.w.e.runtime.kafka.KafkaRuntime$    - message: 1
[info] 14:18:28.271 INFO  - i.w.e.runtime.kafka.KafkaRuntime$    - message: 2
[info] 14:18:29.909 INFO  - i.w.e.runtime.kafka.KafkaRuntime$    - ...sleep done
[info] 14:18:29.915 INFO  - i.w.e.runtime.kafka.KafkaRuntime$    - Consumer done: Success(Vector((), ()))
[info] 14:18:59.937 INFO  - i.w.e.runtime.kafka.KafkaRuntime$    - producer result: Done
[info] 14:18:59.938 INFO  - i.w.e.runtime.kafka.KafkaRuntime$    - consumer shutdown result: Done
[info] 14:18:59.943 INFO  - akka.actor.RepointableActorRef       - Message [akka.kafka.KafkaConsumerActor$Stop$] from Actor[akka://default/system/StreamSupervisor-0/$$a#1381422121] to Actor[akka://default/system/kafka-consumer-1#333391887] was not delivered. [1] dead letters encountered. If this is not an expected behavior, then [Actor[akka://default/system/kafka-consumer-1#333391887]] may have terminated unexpectedly, This logging can be turned off or adjusted with configuration settings 'akka.log-dead-letters' and 'akka.log-dead-letters-during-shutdown'.
[info] 14:18:59.969 INFO  - i.w.e.runtime.kafka.KafkaRuntime$    - system terminated
[info] 14:18:59.969 INFO  - i.w.e.runtime.kafka.KafkaRuntime$    - Success(Terminated(Actor[akka://default/]))
```

### Reproducible Test Case

```scala
import akka.Done
import akka.actor.ActorSystem
import akka.kafka.scaladsl.{Consumer, Producer}
import akka.kafka.{ConsumerSettings, ProducerSettings, Subscriptions}
import akka.stream.ActorMaterializer
import akka.stream.scaladsl.{Keep, Sink, Source}
import com.typesafe.scalalogging.Logger
import org.apache.kafka.clients.consumer.{ConsumerConfig, ConsumerRecord}
import org.apache.kafka.clients.producer.{ProducerConfig, ProducerRecord}
import org.apache.kafka.common.TopicPartition
import org.apache.kafka.common.serialization.{StringDeserializer, StringSerializer}

import scala.concurrent.Future

object KafkaRuntime {

  final val log = Logger(getClass)

  def main(args: Array[String]): Unit = {
    implicit val system = ActorSystem()
    implicit val mat = ActorMaterializer()
    implicit val ec = system.dispatcher
    val bootstrapServers = "localhost:9092"
    val consumerConfig = system.settings.config.getConfig("akka.kafka.consumer")
    val topic = "testtopic"
    val fromOffset = 0L
    val consumerSettings = ConsumerSettings(consumerConfig, new StringDeserializer, new StringDeserializer)
      .withBootstrapServers(bootstrapServers)
      .withGroupId("group1")
      .withProperty(ConsumerConfig.AUTO_OFFSET_RESET_CONFIG, "earliest")

    val producerConfig = system.settings.config.getConfig("akka.kafka.producer")
    val producerSettings = ProducerSettings(producerConfig, new StringSerializer, new StringSerializer)
      .withBootstrapServers(bootstrapServers)
      .withProperty(ProducerConfig.COMPRESSION_TYPE_CONFIG, "snappy")

    val producerDone: Future[Done] =
      Source(1 to 2)
        .map(_.toString)
        .map(value => new ProducerRecord[String, String](topic, value))
        .runWith(Producer.plainSink(producerSettings))
    producerDone.onComplete{ done =>
      log.info(s"Producer done: $done")
    }

    val (control, consumerResults) = Consumer
      .plainSource(
        consumerSettings,
        Subscriptions.assignmentWithOffset(
          new TopicPartition(topic, /* partition = */ 0) -> fromOffset
        )
      )
      .mapAsync(1)(businessLogicAndStoreOffset)
      .toMat(Sink.seq)(Keep.both)
      //.mapMaterializedValue(DrainingControl.apply)
      .run()

    consumerResults.onComplete{ results =>
      log.info(s"Consumer done: $results")
    }

    log.info("sleeping 2 sec...")
    Thread.sleep(2000)
    log.info("...sleep done")

    for{
      producerResult <- producerDone
      shutdownResult <- control.shutdown()
    } yield{
      log.info(s"producer result: $producerResult")
      log.info(s"consumer shutdown result: $shutdownResult")
      mat.shutdown()
      system.terminate().onComplete{ result =>
        log.info("system terminated")
        log.info(result.toString)
      }
    }
  }

  def businessLogicAndStoreOffset(record: ConsumerRecord[String, String]): Future[Unit] = {
    log.info(s"message: ${record.value()}")
    Future.unit
  }
}

```

**Comment by tayvs** [comment] 2019-06-20 12:50
@francisdb this time is configurable. look at 'stop-timeout' https://doc.akka.io/docs/akka-stream-kafka/current/consumer.html

**Comment by francisdb** [comment] 2019-06-22 15:20
@tayvs is see no reason for it to wait any longer once the stream has finished.

**Comment by tayvs** [comment] 2019-06-23 12:49
@francisdb I make some research and found that this delay originally was created because of partitionedSource. Here pr https://github.com/akka/alpakka-kafka/pull/673 and issue https://github.com/akka/alpakka-kafka/issues/672

@ennru Is there any sense to use 'stop-timeout' for flat sources?

**Comment by francisdb** [comment] 2019-06-24 06:41
I guess this dead letter is also unexpected?

**Comment by ennru** [comment] 2019-06-24 08:48
This behaviour is indeed expected and as designed.

The stop timeout is needed when committing is used without a draining control. Otherwise the consumer is shut down before is commits get sent to the Kafka broker.
The timeout is a bit large for smaller setups.

The dead letter is expected as `Stop` is sent from two places right now. I haven't found an easy enough way to avoid that.

**Comment by ennru** [comment] 2019-07-01 14:46
As this is expected behaviour, I'll close this issue.
The documentation recommends to set it to 0 when using the `DrainingControl` https://doc.akka.io/docs/alpakka-kafka/current/consumer.html#draining-control

**Closed by ennru** 2019-07-01 14:46 UTC
