### ISSUE TITLE
Silent failure when commit times out

### ISSUE THREAD

**Issue by Reeebuuk** [akka/alpakka-kafka#1166] opened 2020-07-31 09:22 UTC
We're having problems with kafka source which silently just stops consuming.

![image](https://user-images.githubusercontent.com/4258469/89020504-4f884900-d31f-11ea-8cda-e1101f35f133.png)

So in scenarios where offset commit timeouts we don't have a way of recovering/restarting the stream.

Stream definition:

      val consumerControl = Consumer
        .committableSource(consumerSettings, Subscriptions.topics(sourceTopic))
        .via(eventsFlowTopology)
        .withAttributes(supervisionStrategy(decider))
        .toMat(Committer.sink(CommitterSettings(context.system)))(Keep.both)
        .mapMaterializedValue(x => DrainingControl.apply(x))
        .run()

The `decider` handler in this case is not called.

### Versions used 

akka: 2.6.8
akka-stream-kafka: 2.0.4

### Expected Behavior

We would expect an exception or some way of detecting this scenario.

### Actual Behavior

Source silently stops consuming with no exception.

**Comment by ennru** [comment] 2020-08-03 13:13
Thank you for reporting. At least the `is to be retried` log output looks broken.

The logic for retrying commits was added recently in #1111.

We'll need to investigate this further.

**Comment by seglo** [comment] 2020-08-04 20:14
Hi @Reeebuuk.  I spent some time considering this issue.

This workflow is tricky to reproduce since the `TimeoutException` in this case is propagated from the server.  A commit that took place on the broker itself timed out, not a commit request from the consumer to the broker.  In any case, the retrying of commits in Alpakka Kafka should still work since `TimeoutException` and `DisconnectException` are retriable.

I assume the order of operations in your log screenshot is from bottom to top.  If that's the case then the Consumer `Source` has completed for some reason that's not apparent in the provided snippet.  Can you provide any additional logging from Alpakka Kafka (`akka.kafka`) or the Kafka Consumer (`org.apache.kafka.clients.consumer`) that lead up to this point?  It may contain relevant information that lead to the completion.  At the same time it may worth increasing the log level to `DEBUG` for both to get more verbose logging.

More information about your supervision strategy would be useful.  Not all stream operators implement support for supervision strategies.  If unhandled exceptions occur within Alpakka Kafka `Source` stages, or the `KafkaConsumerActor`, then the whole stream will be failed.  If there is an unhandled exception triggering stream completion you should be able to see it propagate through your supervision strategy, or as a `Failure` in the `DrainingControl.streamCompletion` `Future` of your `consumerControl`.  I would suggest adding some logging here to see if an exception is returned here when the stream shuts down.

Finally, if your goal of implementing a supervision strategy is to recover the stream due to transient network related errors, then I would suggest restarting the stream using [the `RestartSource` as documented in Alpakka Kafka](https://doc.akka.io/docs/alpakka-kafka/current/errorhandling.html#restarting-the-stream-with-a-backoff-stage).

Hope that helps.

**Comment by Reeebuuk** [comment] 2020-08-05 10:56
Hi @seglo for taking the time. We can increase logging but will need to rollout logback changes to PRD (since ofc it's happening there exclusively) which will take some time.

**Comment by seglo** [comment] 2020-08-05 13:27
You're welcome. Your supervision strategy appears to be logging all stream exceptions. Are either of those log lines present in your logs before the source `Completing` message?  If not it leads me to think something else is sending a stream completion signal, and it's not shutting down due to an exception.

**Comment by Reeebuuk** [comment] 2020-08-05 13:34
I have not seen any exceptions being logged, that's the weird thing about it.

Meanwhile I rewrote the implementation as you suggested to use `RestartSource`

     private val control = new AtomicReference[Consumer.Control](Consumer.NoopControl)

     private val result = RestartSource
       .onFailuresWithBackoff(minBackoff = 3.seconds, maxBackoff = 30.seconds, randomFactor = 0.2) { () =>
         val subscription = Subscriptions.topics(sourceTopic)
         Consumer
           .committableSource(consumerSettings, subscription)
           .mapMaterializedValue(c => control.set(c))
           .via(eventsFlowTopology)
           .withAttributes(supervisionStrategy(decider))
           .via(Committer.flow(CommitterSettings(context.system)))
       }
       .runWith(Sink.ignore)

Will put it in prod in a week or two and see did it made a difference.

**Comment by seglo** [comment] 2020-08-05 14:51
Ok. The decider can still be used to log the exception, so I would recommend making sure that's working correctly before pushing code to your prod environment (i.e. introduce an exception and see it log).  You could also use the [`log` operator](https://doc.akka.io/docs/akka/current/stream/stream-error.html#logging-errors) to log exceptions, otherwise I'm not sure how you will ever see stream failures when using the `RestartSource`.

We can keep this issue open for a little while in case you or someone else experiences the issue again.

**Comment by Reeebuuk** [comment] 2020-08-05 15:06
We can even close it for now and I'll reopen if needed. 
Just so you guys can have your backlog somewhat clean :)

**Comment by seglo** [comment] 2020-08-05 15:40
Ok, in that case I'll close it ;)

Best of luck.

**Closed by seglo** 2020-08-05 15:40 UTC

**Comment by elifkus** [comment] 2022-01-31 10:42
We have to same issue and our code looks very similar to yours @Reeebuuk 

Were you able to resolve the issue? If yes, how?

**Comment by Reeebuuk** [comment] 2022-01-31 10:45
@elifkus the problem on our side was that the supervision strategy for the stream was Restart which was causing the message to be dropped because it restarted only that flow in the stream and when we moved to Stop it stopped the whole stream which got caught by supervisor.
After the stop the stream would start where it left off and no issues since :)

**Comment by elifkus** [comment] 2022-01-31 14:40
Thank you for your fast answer. 🙂

**Comment by omeraha** [comment] 2022-11-08 09:14
@Reeebuuk we also suffer from a similar issue, this is our supervision strategy:
```scala
 val resumeOnFailureStrategy: Supervision.Decider = { case t =>
    log.warn("Failure in emitted stream item", t)
    Supervision.Resume
  }
```
The log above is not being issued, and we suspect it means we don't reach the supervision strategy code.
You mentioned that before making the change, you also didn't see any logs from the supervisor code.
Can you explain/share the code that uses Stop and how it solves this issue?

**Comment by Reeebuuk** [comment] 2022-11-08 09:50
Only thing that pops to my mind is that you didn't wire the strategy correctly into the topology?
Try changing it to .Stop and see if the stream ever stops.

**Comment by omeraha** [comment] 2022-11-08 11:42
This is how we wired it:
```scala
...
  .withAttributes(ActorAttributes.supervisionStrategy(resumeOnFailureStrategy))
  .via(Committer.flow(committerSettings))
  .toMat(Sink.ignore)(Keep.right)
  .run()
```

**Comment by omeraha** [comment] 2022-11-09 07:18
@elifkus dd you manage to resolve this?

**Comment by omeraha** [comment] 2022-11-09 10:28
@Reeebuuk 
Can you share your supervision strategy and how you wired it?

**Comment by Reeebuuk** [comment] 2022-11-09 10:38
It's nothing special, identical to yours

```
  protected val decider: Supervision.Decider = {
    case ex =>
      contextLogger.error("Got exception in view builder flow, stream will be stopped", ex)
      Supervision.Stop
  }
```

**Comment by omeraha** [comment] 2022-11-09 10:58
@Reeebuuk thanks.
But say the issue is a transient one (my case - offset commit timed out on the broker), what makes the tread restart?

**Comment by elifkus** [comment] 2022-11-09 15:22
We did resolve it. In our case the problem was that the Kafka consumer was shut down but the application would continue to run. I removed the supervision strategy altogether. The stream stops when it receives an error as it was required to be. 

In our case the issue was that the logic after the stream kept the application running. Once I deleted that part of the code everything worked as expected again.
