### ISSUE TITLE
Surface all Kafka errors 

### ISSUE THREAD

**Issue by jchapuis** [akka/alpakka-kafka#814] opened 2019-05-22 11:55 UTC
### Versions used 

1.0.3

### Expected Behavior

Errors such as `UNKNOWN_TOPIC_OR_PARTITION` or broker unavailable are surfaced in the source instead of generating an warning and assuming that automatic recovery is the desired behavior. This allows dealing with such exceptional cases explicitly with e.g. `RestartSource`.   

### Actual Behavior

NetworkClient repeatedly logs an `WARN` entry of the form `Error while fetching metadata with correlation id 820 : {topicName=UNKNOWN_TOPIC_OR_PARTITION}
[info] 2019-05-22 13:52:37,621 [dispatcher-31] WARN`

**Comment by 2m** [comment] 2019-05-22 12:31
This is a duplicate of #796.

**Comment by 2m** [comment] 2019-05-22 12:32
Thanks for the additional information. It will be useful when working on a fix for this.

**Comment by ennru** [comment] 2019-09-05 06:22
This is implemented with #887, though I do not believe `Error while fetching metadata with correlation id` surfaces as an error. It is "just" a warning.

**Closed by ennru** 2019-09-05 06:22 UTC
