### ISSUE TITLE
Benchmarks work only for 1-partitioned topics (low performance for more partitions)

### ISSUE THREAD

**Issue by mowczare** [akka/alpakka-kafka#773] opened 2019-04-19 12:29 UTC
The benchmarks included in `akka.kafka.benchmarks` package do not work when local Kafka cluster config has `num.partitions` > 1. Both producer and consumer hang waiting for an offset equal to number of messages sent (which can never happen in the aforementioned test case).

What's more, I was concerned of the "at-least once batched" consumer performance on my production environment so I was looking for the benchmark results. I found this:
https://docs.google.com/document/d/101VfFarQNFBW23PYaT09MSLtmtsK03r7mViGt2PCa0Q/edit#
and this:
https://docs.google.com/spreadsheets/d/1SJDQsPHaKyCLBEkPQvBay3thq6I3Xvm_EzuIh1nuKMA/edit#gid=0
456,695 messages per second was an out-of-space number comparing to my 1k per second production (64-partitions topics) experiences. 

So I hotfixed the benchmarks and run the `XKafkaBatchedConsumer`'like tests locally on both 1-partition and 8-partition topics.

Below are the results (considering the benchmark doesn't work on any other number of partitions than 1, I assume the previously reported results pertained to the topic with 1 partition, please verify):

| name of the test | number of partitions | msgs/s previously reported in sheet | msgs/s on my local machine |
| - | - | - | - |
| ApacheKafkaBatchedConsumer | 1 | 1,194,331 | 1,108,237 |
| ApacheKafkaBatchedConsumer | 8 | - | 1,642,036 |
| AlpakkaKafkaBatchedConsumer | 1 | 456,695 | 75,956 |
| AlpakkaKafkaBatchedConsumer | 8 | - | 1017 |

The nature of the consumption is also very curious. I've managed to observe it using the Kafka Tool consumers lag feature and only one partition is consumed immediately, whereas others are consumed very slowly (500 messages per half a second, sequentially).

This seems to affect only this connector, similar ones (like https://github.com/monix/monix-kafka) work fine and performant.

**Comment by 2m** [comment] 2019-04-19 12:40
Really appreciate the analysis. We have dedicated time in this sprint to work on the performance of this connector so this is very timely and helpful.

Also would you mind creating a PR with fixed benchmarks for the multi-partition topics?

**Comment by mowczare** [comment] 2019-04-19 13:23
Sure:
https://github.com/akka/alpakka-kafka/pull/774/files

I stayed with the "number of partitions should be choosed with kafka brokers config" approach.

**Comment by 2m** [comment] 2019-05-09 13:18
I started looking into the benchmarks, and one thing that I will immediately change in the `AlpakkaKafkaBatchedConsumer` test is the use of the `.batch` Akka Stream operator. This operator only batches elements if the downstream is slower. If it is not, then this test ends up committing every message separately.

Instead it should use `Comitter.flow()` ([like shown here](https://doc.akka.io/docs/alpakka-kafka/current/consumer.html#offset-storage-in-kafka-committing)). This flow uses `.groupedWeightedWithin` which does the right thing and also handles the committing.

You can try it in your code and see how much it impacts performance.

**Comment by 2m** [comment] 2019-05-16 09:33
We have incorporated your proposed changes and added a batched consumer benchmark with multiple partitions in #807.

However I am not able to reproduce the decreased performance when running those tests. These are the numbers from my machine:

| benchmark | number of partitions | msgs/s |
| - | - | - |
| ApacheKafkaBatchedConsumer | 1 | 53946 |
| ApacheKafkaBatchedConsumer | 8 | 57154 |
| AlpakkaKafkaBatchedConsumer | 1 | 48802 |
| AlpakkaKafkaBatchedConsumer | 8 | 32511 |

Note that I was only running those with one Kafka node.

Do you still see the same drastic slowdown when running: `benchmarks/dockerComposeTest it:testOnly *.AlpakkaKafkaBatchedConsumer`?

**Comment by mowczare** [comment] 2019-05-16 16:59
Currently I receive very similar results to yours, both with Kafka on bare metal and as a docker container. I assume it was the issue with the `.batch` operator and commiting every single message. 

I believe the example I was following was removed from the documentation.

**Comment by 2m** [comment] 2019-05-17 03:49
I see. Yes, the documentation previously was suggesting the `.batch` operator, but it only batches if the downstream is very slow so it was not the best tool for the job.

I am going to close this ticket then. Feel free to open another one if you find something else that could be improved.

**Closed** 2019-05-17 03:49 UTC
