### ISSUE TITLE
kafka streams creating multiple producer threads

### ISSUE THREAD

**Issue by kolapkardhaval** [akka/alpakka-kafka#920] opened 2019-10-03 00:15 UTC
I am running alpakka kafka producer in akka stream and multiple producer processes are getting run:

"kafka-producer-network-thread | producer-20" #49 daemon prio=5 os_prio=31 tid=0x00007f80562c1800 nid=0x8903 runnable [0x000070000e3f9000]

I am using singleton and not creating multiple kafka producers instances but still seeing 10k kafka-producer-network-thread created. This is causing servers to go to 99% cpu usage.

Code is
`CompletionStage<Done> done =
    Source.range(1, 100)
        .map(number -> number.toString())
        .map(value -> new ProducerRecord<String, String>(topic, value))
        .runWith(Producer.plainSink(producerSettings, kafkaProducer), materializer);`

Do I need to do Producer.close()? If so, where shall I do in this stream?

**Comment by ennru** [comment] 2019-10-03 06:55
When you provide the producer from the outside, its life-cycle becomes your responsibility. So when you don't need the `kafkaProducer` anymore, call close on it.
You shouldn't do it in the stream, I assume you start the stream multiple times and want to re-use that producer instance.

**Comment by kolapkardhaval** [comment] 2019-10-03 18:23
@ennru Thank you for the info. 
1. Is there a way to not provide the producer from outside? Is it using flexi flow? If so, I tried that too and it still created the network threads.
2. For producer from outside, do we close it after sending every msg or few msgs and have a new instance created again?

**Comment by ennru** [comment] 2019-10-08 07:22
1 & 3: The Kafka Producer API creates threads internally, the configuration options for the threading are limited: http://kafka.apache.org/documentation/#producerconfigs

2. No, as long as the stream is running you may not close the producer. Closing it means to call `producer.close(..)`.

**Comment by ennru** [comment] 2019-10-08 07:26
This is not a bug in Alpakka Kafka, please keep the discussion to https://discuss.lightbend.com/t/kafka-streams-creating-multiple-producer-threads/5174

**Closed by ennru** 2019-10-08 07:26 UTC
